#!/usr/bin/env python3
"""
Run this once before starting the server.
Generates bcrypt password hashes and writes your .env file.

Usage:
    python setup_auth.py
"""
import secrets
import getpass
import sys
import os

def main():
    try:
        import bcrypt
    except ImportError:
        print("ERROR: bcrypt not installed. Run: pip install -r requirements.txt")
        sys.exit(1)

    print("=== VocabGraph — Auth Setup ===\n")

    # --- Admin ---
    admin_user = input("Admin username [admin]: ").strip() or "admin"
    while True:
        admin_pass = getpass.getpass(f"Admin password: ")
        if len(admin_pass) >= 8:
            break
        print("  Password must be at least 8 characters.")

    # --- Visitor ---
    visitor_user = input("\nVisitor username [visitor]: ").strip() or "visitor"
    if visitor_user == admin_user:
        print("ERROR: Visitor and admin usernames must be different.")
        sys.exit(1)
    while True:
        visitor_pass = getpass.getpass(f"Visitor password: ")
        if len(visitor_pass) >= 8:
            break
        print("  Password must be at least 8 characters.")

    # --- JWT ---
    jwt_secret = secrets.token_hex(32)
    expire_h   = input("\nToken expiry in hours [8]: ").strip() or "8"
    try:
        expire_h = int(expire_h)
        if expire_h < 1:
            raise ValueError
    except ValueError:
        print("Invalid number, defaulting to 8.")
        expire_h = 8

    print("\nHashing passwords (this takes a second)…")
    admin_hash   = bcrypt.hashpw(admin_pass.encode(),   bcrypt.gensalt(rounds=12)).decode()
    visitor_hash = bcrypt.hashpw(visitor_pass.encode(), bcrypt.gensalt(rounds=12)).decode()

    env_path = os.path.join(os.path.dirname(__file__), ".env")

    env_content = f"""# VocabGraph — Auth Configuration
# Generated by setup_auth.py
# KEEP THIS FILE SECRET — never commit it to git

JWT_SECRET={jwt_secret}
JWT_EXPIRE_HOURS={expire_h}

ADMIN_USERNAME={admin_user}
ADMIN_PASSWORD_HASH={admin_hash}

VISITOR_USERNAME={visitor_user}
VISITOR_PASSWORD_HASH={visitor_hash}
"""

    with open(env_path, "w", encoding="utf-8") as f:
        f.write(env_content)

    print(f"\n✓ Written to {env_path}")
    print(f"  Admin user   : {admin_user}")
    print(f"  Visitor user : {visitor_user}")
    print(f"  Token expiry : {expire_h} hours")
    print("\nNow run:  pip install -r requirements.txt")
    print("Then run: uvicorn main:app --host 0.0.0.0 --port 8000")

if __name__ == "__main__":
    main()
